// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieCDN.Database;

#nullable disable

namespace MovieCDN.Database.Migrations
{
    [DbContext(typeof(MovieCdnContext))]
    [Migration("20250803062903_0308202501")]
    partial class _0308202501
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MovieCDN.Database.ApiKey", b =>
                {
                    b.Property<string>("ClientId")
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ClientId");

                    b.Property<string>("SecretKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("SecretKey");

                    b.HasKey("ClientId");

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("MovieCDN.Database.File", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Id");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("FileName");

                    b.Property<string>("PartitionKey")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("PartitionKey");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Type");

                    b.HasKey("Id");

                    b.ToTable("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
