// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieCDN.Database;

#nullable disable

namespace MovieCDN.Database.Migrations
{
    [DbContext(typeof(MovieCdnContext))]
    [Migration("20250801095630_0108202501")]
    partial class _0108202501
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MovieCDN.Database.ApiKey", b =>
                {
                    b.Property<string>("ClientId")
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ClientId");

                    b.Property<string>("SecretKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("secretKey");

                    b.HasKey("ClientId");

                    b.ToTable("ApiKeys");
                });
#pragma warning restore 612, 618
        }
    }
}
